# Generated by Django 4.0.6 on 2022-08-13 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipocuenta',
            options={'managed': False, 'ordering': ['act_id'], 'verbose_name': 'Tipo de Cuenta', 'verbose_name_plural': 'Tipos de Cuenta'},
        ),
    ]
