# Generated by Django 4.0.6 on 2022-08-13 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0003_alter_cuenta_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuenta',
            options={'managed': True, 'ordering': ['account_id'], 'verbose_name': 'Cuenta', 'verbose_name_plural': 'Cuentas'},
        ),
        migrations.AlterModelOptions(
            name='tipocuenta',
            options={'managed': True, 'ordering': ['act_id'], 'verbose_name': 'Tipo de Cuenta', 'verbose_name_plural': 'Tipos de Cuenta'},
        ),
    ]
